# Generated by Django 5.2.7 on 2025-10-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_quiz",
                to="api.topic",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="chapter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_quiz",
                to="api.chapter",
            ),
        ),
    ]
