# Generated by Django 5.2.7 on 2025-10-29 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_quizattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="article_content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
